# Generated by Django 3.1.5 on 2021-01-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210121_0501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
