# Generated by Django 3.1.5 on 2021-01-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_value',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
