# Generated by Django 3.1.5 on 2021-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210212_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_reference',
            field=models.TextField(blank=True),
        ),
    ]
