# Generated by Django 3.1.5 on 2021-02-04 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address_street1', models.CharField(max_length=255)),
                ('address_street2', models.CharField(blank=True, max_length=255)),
                ('address_suburb', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
                ('address_postcode', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
